SELECT * FROM HR;

-- OVERALL ATTRITION HAPPENED IN MY THE COMPANY
SELECT COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITIONCOUNT,
       COUNT(*) AS TOTAL_EMPLOYEES
FROM HR;

-- PRESENCE OF OVERTIME AND CORRELATION IN ATTRITION
SELECT OVERTIME, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR
WHERE ATTRITION = 1
GROUP BY OVERTIME

-- GENDER DISTRIBUTION IN THE COMPANY
SELECT GENDER, COUNT(*) AS TOTAL_EMPLOYEES FROM HR
GROUP BY GENDER;

SELECT GENDER, COUNT(*) FROM HR
WHERE ATTRITION = 1
GROUP BY GENDER;


SELECT * FROM HR;

-- THERE IS A NEGATIVE CORRELATION AMONGST PERFORMANCE RATING AND ATTRITION
SELECT PERFORMANCERATING, COUNT(CASE WHEN ATTRITION = 1 THEN 1 END) AS ATTRITION_COUNT
FROM HR
GROUP BY PerformanceRating;

-- ATTRITION COUNT BASED ON THE JOB ROLES
SELECT DEPARTMENT, JOBROLE, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY JOBROLE, DEPARTMENT
ORDER BY ATTRITION_COUNT DESC;

-- ATTRITION COUNT BASED ON DISTANCE FORM HOME VARIABLE
SELECT DISTANCEFROMHOME, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY DistanceFromHome
ORDER BY ATTRITION_COUNT DESC;

SELECT * FROM HR;

SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1
GROUP BY Department;

-- RELATION OF SALARY AND ATTRITION -- NEGATIVE CORRELATION AMONGST SALARY HIKES AND ATTRITION
SELECT PERCENTSALARYHIKE, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1
GROUP BY PercentSalaryHike
ORDER BY ATTRITION_COUNT DESC;

-- EDUCATION FIELD IS RELATED TO ATTRITION COUNT OR NOT
SELECT EDUCATIONFIELD, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1
GROUP BY EducationField
ORDER BY ATTRITION_COUNT DESC;

USE LBP01;
SELECT * FROM HR;

-- RELATION BETWEEN YEARS IN CURRENT ROLE AND ATTRITION COUNT
SELECT YEARSINCURRENTROLE, COUNT(CASE WHEN ATTRITION = 1 THEN 1 END) AS ATTRITION_COUNT FROM HR
WHERE YEARSINCURRENTROLE > (SELECT AVG(YEARSINCURRENTROLE) FROM HR)
GROUP BY YEARSINCURRENTROLE
ORDER BY ATTRITION_COUNT DESC;
-- EMPLOYEES WHO ARE WORKING IN THE COMPANY FROM LAST 5-10 YEARS HAVE THE HIGHEST ATTRITION COUNT

-- JOB SATISFACTION AND MONTHLY INCOME
SELECT JOBSATISFACTION, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1 AND MonthlyIncome < (SELECT AVG(MONTHLYINCOME) FROM HR)
GROUP BY JobSatisfaction;
-- MONTHLY INCOME PLAYS A VITAL ROLE IN ATTRITION COUNT IRRESPECTIVE THE SATISFACTION FROM THE JOB IS ON THE HIGHER SIDE

SELECT * FROM HR

-- EMPLOYEE ATTRITION BASED ON THE AGE RANGE
SELECT CASE WHEN AGE <= 29 THEN '18-29'
                                 WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
								 WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
								 WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
								 ELSE '60 OR OLDER'
								 END AS 'AGE RANGE', COUNT(*) AS 'NUMBER OF ATTRITION BASED ON AGE RANGE'
FROM HR
WHERE Attrition  = 1 AND YearsAtCompany >= 1
GROUP BY CASE WHEN AGE <= 29 THEN '18-29'
                                 WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
								 WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
								 WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
								 ELSE '60 OR OLDER'
								 END
--ORDER BY 'NUMBER OF ATTRITION BASED ON AGE RANGE' DESC;
ORDER BY COUNT(*) DESC;

SELECT * FROM HR;

SELECT MAX(DAILYRATE) FROM HR
WHERE Attrition = 1;


SELECT MIN(DAILYRATE) FROM HR
WHERE Attrition = 1;


SELECT MAX(MONTHLYRATE)
FROM HR
WHERE Attrition = 1;

SELECT MIN(MONTHLYRATE)
FROM HR
WHERE Attrition = 1;


SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND DailyRate < (SELECT AVG(DAILYRATE) FROM HR) AND MonthlyRate < (SELECT AVG(MONTHLYRATE) FROM HR) AND MonthlyIncome < (SELECT AVG(MONTHLYINCOME) FROM HR);;

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND DailyRate < (SELECT AVG(DAILYRATE) FROM HR)-- AND MonthlyRate < (SELECT AVG(MONTHLYRATE) FROM HR) AND MonthlyIncome < (SELECT AVG(MONTHLYINCOME) FROM HR);;

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND MonthlyRate < (SELECT AVG(MONTHLYRATE) FROM HR) 

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND MonthlyIncome < (SELECT AVG(MONTHLYINCOME) FROM HR);;

SELECT * FROM HR;

SELECT ENVIRONMENTSATISFACTION, RELATIONSHIPSATISFACTION, COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND MONTHLYINCOME < (SELECT AVG(MONTHLYINCOME) FROM HR)
GROUP BY ENVIRONMENTSATISFACTION, RELATIONSHIPSATISFACTION
ORDER BY 'ATTRITION_COUNT' DESC;


SELECT MARITALSTATUS, COUNT(*) AS 'ATTRITION_COUNT'
FROM HR 
WHERE Attrition = 1
GROUP BY MaritalStatus;





